#!/bin/bash
#SBATCH -p SMP
#SBATCH -N1
#SBATCH -c40
#SBATCH --mail-user=zcapjru@ucl.ac.uk
#SBATCH --mail-type=ALL
#SBATCH --mem=1000GB 
python /home/ug19_jrz/montepython2/montepython/MontePython.py run -p input/kids450_bs_2cosmos_mark2.param -o /share/splinter/ug19_jrz/paper_results/2COSMOS/kids_2cosmo -m NS --NS_max_iter 10000000 --NS_sampling_efficiency 0.3 --NS_n_live_points 1000 --NS_evidence_tolerance 0.05
