#!/bin/bash
#SBATCH -N1
#SBATCH -n16
#SBATCH --mail-user=zcapjru@ucl.ac.uk
#SBATCH --mail-type=ALL 
python /home/ug19_jrz/montepython2/montepython/MontePython.py run -p input/kv450_bs_2cosmos_mark3.param -o /share/splinter/ug19_jrz/paper_results/2COSMOS/kv_mark3_test  -m NS --NS_max_iter 10000000 --NS_sampling_efficiency 0.15 --NS_n_live_points 1000 --NS_evidence_tolerance 0.1
